version: 2.1

orbs:
  maven: circleci/maven@0.0.12

shared: &shared
  steps:
    - checkout
    - restore_cache:
        keys:
          - ekryd-cache-{{ checksum "pom.xml" }}
          - ekryd-cache- # fallback in case previous cache key is not found
    - run: mvn clean install -Dmaven.javadoc.skip=true -Dinvoker.skip=true -B -V
    - save_cache:
        paths:
          - ~/.m2
        key: ekryd-cache--{{ checksum "pom.xml" }}
      
jobs:
  jdk17:
    docker:
      - image: cimg/openjdk:17.0
    <<: *shared
  jdk18:
    docker:
      - image: cimg/openjdk:18.0
    <<: *shared
  jdk19:
    docker:
      - image: cimg/openjdk:19.0
    <<: *shared
  jdk11:
    docker:
      - image: cimg/openjdk:11.0
    steps:
      - checkout
      - restore_cache:
          keys:
            - ekryd-cache-{{ checksum "pom.xml" }}
            - ekryd-cache- # fallback in case previous cache key is not found
      - run: mvn clean install -DskipTests=true -Dmaven.javadoc.skip=true -Dinvoker.skip=true -B -V
      - run: mvn clean jacoco:prepare-agent integration-test jacoco:report -B
      - run: mvn coveralls:report -B -DrepoToken=$COVERALLS_REPO_TOKEN
      - run: mvn sonar:sonar -Dsonar.projectKey=com.github.ekryd.echo-maven-plugin:echo-plugin -Dsonar.organization=ekryd-github -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONARCLOUD_TOKEN
      - save_cache:
          paths:
            - ~/.m2
          key: ekryd-cache--{{ checksum "pom.xml" }}
        
workflows:
  version: 2
  work:
    jobs:
      - jdk17
      - jdk18:
          requires:
            - jdk17
      - jdk19:
          requires:
            - jdk17
      - jdk11:
          filters:  # using regex filters requires the entire branch to match
            branches:              
              only:  # only branches matching the below regex filters will run
                - master
          requires:
            - jdk17
            - jdk18
            - jdk19
