version: 2.1

orbs:
  maven: circleci/maven@2.1.1

shared: &shared
  steps:
    - checkout
    - restore_cache:
        keys:
          - ekryd-cache-{{ checksum "pom.xml" }}
          - ekryd-cache- # fallback in case previous cache key is not found
    - run: mvn clean verify -Dmaven.javadoc.skip=true -Dinvoker.skip=true -B -V
    - save_cache:
        paths:
          - ~/.m2
        key: ekryd-cache--{{ checksum "pom.xml" }}

jobs:
  jdk20:
    docker:
      - image: cimg/openjdk:25.0
    <<: *shared
  jdk21:
    docker:
      - image: cimg/openjdk:25.0
    <<: *shared
  jdk22:
    docker:
      - image: cimg/openjdk:25.0
    <<: *shared
  jdk23:
    docker:
      - image: cimg/openjdk:25.0
    <<: *shared
  jdk24:
    docker:
      - image: cimg/openjdk:25.0
    <<: *shared
  jdk17:
    docker:
      - image: cimg/openjdk:25.0
    steps:
      - checkout
      - restore_cache:
          keys:
            - ekryd-cache-{{ checksum "pom.xml" }}
            - ekryd-cache- # fallback in case previous cache key is not found
      - run: mvn clean verify -DskipTests=true -Dmaven.javadoc.skip=true -Dinvoker.skip=true -B -V
      - run: mvn clean jacoco:prepare-agent integration-test jacoco:report -B
      - run: mvn coveralls:report -B -DrepoToken=$COVERALLS_REPO_TOKEN
      - run: mvn sonar:sonar -Dsonar.projectKey=com.github.ekryd.echo-maven-plugin:echo-plugin -Dsonar.organization=ekryd-github -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONARCLOUD_TOKEN
      - save_cache:
          paths:
            - ~/.m2
          key: ekryd-cache--{{ checksum "pom.xml" }}

workflows:
  version: 2
  work:
    jobs:
      - jdk21
      - jdk20:
          requires:
            - jdk21
      - jdk22:
          requires:
            - jdk21
      - jdk23:
          requires:
            - jdk21
      - jdk24:
          requires:
            - jdk21
      - jdk17:
          filters: # using regex filters requires the entire branch to match
            branches:
              only: # only branches matching the below regex filters will run
                - master
          requires:
            - jdk20
            - jdk21
            - jdk22
            - jdk23
            - jdk24
