name: build

on:
  push:
    # Avoid workflow run for _merged_ `dependabot` PRs.
    # They were (hopefully!) already tested in PR-triggered workflow.
    branches-ignore: "dependabot/**"
  pull_request:
    paths-ignore:
      - "**.adoc"
      - "**.md"
      - "**.txt"

permissions:
  contents: write
  pull-requests: write

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: "Echo environment"
        run: |
          echo "${{github.event_name}}"
          echo "${{github.actor}}"
          echo "${{github.event.pull_request.html_url}}"
    
  build:
    # if: github.event_name == 'pull_request' && github.actor == 'dependabot[bot]'
    runs-on: ${{ matrix.os }}
    needs: echo

    strategy:
      matrix:
        os: [ macos-latest, ubuntu-latest, windows-latest ]
        version: [11, 17]

    steps:
      - name: Checkout repository
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c   # 3.3.0

      - name: Setup JDK 11
        uses: actions/setup-java@1df8dbefe2a8cbc99770194893dd902763bee34b   # 3.7.0
        with:
          distribution: temurin
          java-version: ${{ matrix.version }}
          java-package: jdk
          architecture: x64
          cache: maven

      # We could have used `verify`, but `clean install` is required while generating the build reproducibility report, which is performed in the next step.
      # For details, see: https://maven.apache.org/guides/mini/guide-reproducible-builds.html#how-to-test-my-maven-build-reproducibility
      - name: Build
        shell: bash
        run: |
          ./mvnw \
            --show-version --batch-mode --errors --no-transfer-progress \
            -DtrimStackTrace=false \
            -DinstallAtEnd=true \
            clean install
            
  merge:
    # if: github.event_name == 'pull_request' && github.actor == 'dependabot[bot]'
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: "Echo environment"
        run: |
          echo "${{github.event_name}}"
          echo "${{github.actor}}"

      - name: "[dependabot] Fetch metadata"
        id: metadata
        uses: dependabot/fetch-metadata@v1.3.6
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"

      - name: "[dependabot] Auto-merge the PR"
        run: gh pr merge --auto --squash "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
